
function(find_resource_dirs out_res_dirs search_dir)
  set(res_dirs "")
  macro(find_resource_dirs_iterator current_dir)
    file(GLOB names RELATIVE ${search_dir} ${current_dir}/*)
    foreach (name ${names})
      get_filename_component(filename "${name}" NAME)
      if (IS_DIRECTORY ${search_dir}/${name})
        string(TOLOWER "${filename}" filename_lower)
        if (filename_lower STREQUAL "resources")
          list(APPEND res_dirs "${name}")
        else ()
          find_resource_dirs_iterator("${search_dir}/${name}")
        endif ()
      endif ()
    endforeach ()
  endmacro()
  find_resource_dirs_iterator(${search_dir})
  set(${out_res_dirs} "${res_dirs}" PARENT_SCOPE)
endfunction()
